export { default as SEARCH } from './search.svg';
export { default as PENCIL } from './pencil.svg';
export { default as ARROW_BACK } from './arrow_back.svg';
export { default as LIST_MENU } from './list_menu.svg';
export { default as H1 } from './h1.svg';
export { default as H2 } from './h2.svg';
export { default as H3 } from './h3.svg';
export { default as H4 } from './h4.svg';
export { default as DOT } from './dot.svg';
